export const CATEGORY_CHOSEN = 'CATEGORY_CHOSEN';
export const SUB_CATEGORY_CHOSEN = 'SUB_CATEGORY_CHOSEN';
export const SUB_CATEGORY_HOVER = 'SUB_CATEGORY_HOVER';
export const SUB_CATEGORY_UN_HOVER = 'SUB_CATEGORY_UN_HOVER';
export const ROTATE_UPDATED = 'ROTATE_UPDATED';
export const DEV_MODE = 'DEV_MODE';
